/* AUTO GENERATED by scripts/filter.py */

#include <stdint.h>

#define DOWNSAMPLE_TAPS 19u

static const unsigned int downsample_taps = DOWNSAMPLE_TAPS;
static const unsigned int numCoeffUnique  = 6u;
static const int16_t      firCoeffs[6] = {92, -279, 957, -2670, 10113, 16339};
