name: build-emonPiTx-firmware

on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build with Arm toolchain
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install toolchain
              run: |
                sudo apt-get update
                sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

            - name: Verify installation
              run: arm-none-eabi-gcc --version

            - name: Build firmware
              run: |
                make -j

            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: firmware-${{ github.ref_name }}
                path: bin/emon32*.*
